[wokwi]
version = 1
firmware = '.pio/build/esp32dev/firmware.bin'
elf = '.pio/build/esp32dev/firmware.elf'

[[parts]]
type = "wokwi-esp32-devkit-v1"
id = "esp"
top = 50
left = 100

[[parts]]
type = "wokwi-dht22"
id = "dht"
top = 70
left = 350

[[parts]]
type = "wokwi-slide-switch"
id = "vibration"
top = 170
left = 350

[[parts]]
type = "wokwi-photoresistor-sensor"
id = "ldr"
top = 270
left = 350 